seed:
    image: y12docker/bitcoind:0.10.1
    volumes:
        - blockchain:/btc/data
    command: >
        bitcoind -regtest -txindex -disablewallet -port=18333
        -conf=/btc/bitcoin.conf -datadir=/btc/data
        -rpcallowip=172.17.0.0/16 -rpcport=18332
abe:
    build: abe
    volumes_from:
        - seed
    ports:
        - 8582:80

nginx:
    build: nginx
    ports:
        - 80:80
    links:
        - abe
        - faucet
    environment:
        - Y_NGINX_SERVER_NAME=192.168.2.73
        - Y_NGINX_SERVER_PORT=80
        - Y_ABE_HOST=abe
        - Y_ABE_PORT=80
        - Y_FAUCET_HOST=faucet
        - Y_FAUCET_PORT=8581

alice:
    image: y12docker/bitcoind:0.10.1
    links:
        - seed
    command: >
        bitcoind -regtest -port=18333
        -conf=/btc/bitcoin.conf -datadir=/btc/data
        -addnode=seed:18333
        -rpcallowip=172.17.0.0/16 -rpcport=18332

bob:
    image: y12docker/bitcoind:0.10.1
    links:
        - alice
    command: >
        bitcoind -regtest -port=18333
        -conf=/btc/bitcoin.conf -datadir=/btc/data
        -addnode=alice:18333
        -rpcallowip=172.17.0.0/16 -rpcport=18332

keeper:
    image: y12docker/bitcoind:0.10.1
    links:
        - seed
    command: >
        bitcoind -regtest -port=18333
        -conf=/btc/bitcoin.conf -datadir=/btc/data
        -addnode=seed:18333
        -rpcallowip=172.17.0.0/16 -rpcport=18332

cron:
    build: cron
    links:
        - keeper

faucet:
    build: faucet
    links:
        - keeper
    ports:
        - 8581:8581
