FROM y12docker/pbase:15.03
# https://github.com/phusion/baseimage-docker
# bitpay/bitcore
# https://github.com/bitpay/bitcore
RUN mkdir /opt/bitcore
WORKDIR /opt/bitcore
RUN sudo npm install bitcore
RUN sudo npm install bitcore-explorers
# ---------- cleanup --------------
#
# Clean up APT when done.
RUN apt-get autoremove -y && apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
