FROM gliderlabs/alpine:3.1

WORKDIR /myapp
ADD requirements.txt /myapp/

RUN apk-install python py-pip openssl ca-certificates
RUN apk-install --virtual build-dependencies python-dev build-base wget \
  && pip install -r requirements.txt \
#  && python setup.py install \
  && apk del build-dependencies

# CMD ["myapp", "start"]
