web1:
    hostname: web1
    image: y12docker/apbase:1504
    command: python -m SimpleHTTPServer
    ports:
        - "8000:8000"
    environment:
        - SERVICE_NAME=web1
        - SERVICE_TAGS=web,test

web2:
    hostname: web2
    image: y12docker/apbase:1504
    command: python -m SimpleHTTPServer
    ports:
        - "8001:8000"
    environment:
        - SERVICE_NAME=web2
        - SERVICE_TAGS=web,test

consul:
    image: progrium/consul
    hostname: consul
    ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
    command: -server -bootstrap -ui-dir /ui

registrator:
  image: gliderlabs/registrator
  links:
      - consul
  volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  command: consul://consul:8500

test:
    hostname: test
    image: y12docker/apbase:1504
    command: nosetests -v /app/test_http.py
    volumes:
        - app/:/app
    links:
        - web1
        - web2
        - consul
