pyapp:
    build: pyapp
    links:
        - influx
    environment:
        INFLUXDB_HOST: influx
        INFLUXDB_DB: db1

influx:
    image: tutum/influxdb:0.8.8
    ports:
        - "8083:8083"
        - "8086:8086"
    environment:
        PRE_CREATE_DB: "db1;db2"
