seed2taipei:
    image: y12docker/bitcoind:0.10.1
    volumes:
        - blockchain/taipei:/btc/data
    command: >
        bitcoind -regtest -txindex -disablewallet -port=18333
        -conf=/btc/bitcoin.conf -datadir=/btc/data
        -rpcallowip=172.17.0.0/16 -rpcport=18332

seed2taichung:
    image: y12docker/bitcoind:0.10.1
    volumes:
        - blockchain/taichung:/btc/data
    command: >
        bitcoind -regtest -txindex -disablewallet -port=18333
        -conf=/btc/bitcoin.conf -datadir=/btc/data
        -rpcallowip=172.17.0.0/16 -rpcport=18332

keeper2taipei:
    image: y12docker/bitcoind:0.10.1
    links:
        - seed2taipei
    command: >
        bitcoind -regtest -port=18333
        -conf=/btc/bitcoin.conf -datadir=/btc/data
        -addnode=seed2taipei:18333
        -rpcallowip=172.17.0.0/16 -rpcport=18332

keeper2taichung:
    image: y12docker/bitcoind:0.10.1
    links:
        - seed2taipei
    command: >
        bitcoind -regtest -port=18333
        -conf=/btc/bitcoin.conf -datadir=/btc/data
        -addnode=seed2taipei:18333
        -rpcallowip=172.17.0.0/16 -rpcport=18332

abe2taipei:
    build: abe
    volumes_from:
        - seed2taipei
    ports:
        - 8681:80

abe2taichung:
    build: abe
    volumes_from:
        - seed2taichung
    ports:
        - 8682:80

cron2taipei:
    build: cron
    links:
        - keeper2taipei
    environment:
        - Y_KEEPER_HOST=keeper2taipei
        - Y_KEEPER_PORT=18332
        - Y_KEEPER_USER=user
        - Y_KEEPER_PASS=pass

cron2taichung:
    build: cron
    links:
        - keeper2taichung
    environment:
        - Y_KEEPER_HOST=keeper2chung
        - Y_KEEPER_PORT=18332
        - Y_KEEPER_USER=user
        - Y_KEEPER_PASS=pass

faucet2taipei:
    build: faucet
    links:
        - keeper2taipei
    ports:
        - 8581:8581
    environment:
        - Y_KEEPER_HOST=keeper2taipei
        - Y_KEEPER_PORT=18332
        - Y_KEEPER_USER=user
        - Y_KEEPER_PASS=pass

faucet2taichung:
    build: faucet
    links:
        - keeper2taichung
    ports:
        - 8582:8581
    environment:
        - Y_KEEPER_HOST=keeper2taichung
        - Y_KEEPER_PORT=18332
        - Y_KEEPER_USER=user
        - Y_KEEPER_PASS=pass

nginx:
    build: nginx
    ports:
        - 80:80
    links:
        - abe2taipei
        - abe2taichung
        - faucet2taipei
    environment:
        - Y_NGINX_SERVER_NAME=192.168.2.73
        - Y_NGINX_SERVER_PORT=80
        - Y_ABE_HOST=abe2taipei
        - Y_ABE_PORT=80
        - Y_FAUCET_HOST=faucet2taipei
        - Y_FAUCET_PORT=8581
